### ISSUE TITLE
add `@ota-meshi/eslint-plugin-svelte`

### ISSUE THREAD

**Issue by u-sho** [u-sho/quantum-game-arena#51]
## TODO

Info: https://ota-meshi.github.io/eslint-plugin-svelte/

- [ ] `npm i -D @ota-meshi/eslint-plugin-svelte`
- [ ] add `"plugin:@ota-meshi/svelte/recommended"` to `extends` field of `.eslintrc.cjs`
- [x] add auto lint-fix vscode setting

**Comment by u-sho** [comment]
公式化されてた

https://github.com/sveltejs/eslint-plugin-svelte/releases/tag/v2.0.0

**Comment by u-sho** [comment]
merged #138
